 services:
  api:
    build:
      context: .
      dockerfile: TaskManagement.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=TaskManagement;Username=admin;Password=admin
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: taskmanagement_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: TaskManagement
    ports:
      - "5432:5432"

