version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: TaskManagement.API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: taskmanagement_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: TaskManagement
    ports:
      - "5432:5432"
