 services:
  api:
    build:
      context: .
      dockerfile: TaskManagement.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TaskManagement;User Id=sa;Password=YourStrong(!)Password;Encrypt=False
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanagement_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong(!)Password"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"

